### PR TITLE
Set strict mode and use appstream for version, summary, and description.

### PR DESCRIPTION
**Pull request by kenvandine**

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
Well, there is actually lots of issue in the `paper` snap if built without any changes. But the prefix is necessary to be changed so that, it actually works, takes the snaps paths into consideration. I don't know if it'll work or not. I will actually need to change the dbus `exec` path then. Also, the description & summary isn't perfect yet. Kindly keep the `--prefix` unchanged. 

Have you tested it locally? It builds without `gobject-introspection`?

**Comment by kenvandine** [comment]
> Well, there is actually lots of issue in the `paper` snap if built without any changes. But the prefix is necessary to be changed so that, it actually works, takes the snaps paths into consideration. I don't know if it'll work or not. I will actually need to change the dbus `exec` path then. Also, the description & summary isn't perfect yet. Kindly keep the `--prefix` unchanged.
> 
> Have you tested it locally? It builds without `gobject-introspection`?

Yes, gobject-introspection is included in the gnome-42-2204-sdk snap (I am the maintainer of that build-snap as well as the gnome extension).

The prefix hack shouldn't be necessary anymore, that is something we did in the past for some snaps but those issues should work properly with the gnome extension.

**Comment by soumyaDghosh** [comment]
Well, that's great, thanks for your PR. BTW, would like another help. Can you help me with this one?
``````
[1/41] Compiling Vala source ../src/src/Application.vala ../src/src/MainWindow.vala ../src/src/Models/Note.vala ../src/src/Models/Notebook.vala ../src/src/Models/Trash.vala ../src/src/Repositories/NoteRepository.vala ../src/src/Repositories/NotebookRepository.vala ../src/src/Repositories/TrashRepository.vala ../src/src/Services/MigrationManager.vala ../src/src/Services/SettingsManager.vala ../src/src/Services/StyleManager.vala ../src/src/Utils/FileUtils.vala ../src/src/Utils/FormatUtils.vala ../src/src/Utils/MiscUtils.vala ../src/src/Utils/NoteSorter.vala ../src/src/Utils/ObservableList.vala ../src/src/Utils/ThreadUtils.vala ../src/src/Utils/TimeUtils.vala ../src/src/ViewModels/NoteViewModel.vala ../src/src/ViewModels/NotebookViewModel.vala ../src/src/ViewModels/TrashViewModel.vala ../src/src/Views/NoteContentView.vala ../src/src/Views/NoteGridView.vala ../src/src/Views/NoteListView.vala ../src/src/Views/NotebookListView.vala ../src/src/Views/NotebookMainListView.vala ../src/src/Views/NotebookMoveListView.vala ../src/src/Views/TrashContentView.vala ../src/src/Views/TrashListView.vala ../src/src/Views/View.vala ../src/src/Widgets/EditNotebookDialog.vala ../src/src/Widgets/NoteGridRowContent.vala ../src/src/Widgets/NoteRowBadge.vala ../src/src/Widgets/NoteRowContent.vala ../src/src/Widgets/MoveToDialog.vala ../src/src/Widgets/NotebookRowContent.vala ../src/src/Widgets/NoteTheme.vala ../src/src/Widgets/TrashRowBadge.vala ../src/src/Widgets/TrashRowContent.vala                                                                                                                                                        
2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.970 :: FAILED: io.github.lainsce.Notejot.p/src/Application.c io.github.lainsce.Notejot.p/src/MainWindow.c io.github.lainsce.Notejot.p/src/Models/Note.c io.github.lainsce.Notejot.p/src/Models/Notebook.c io.github.lainsce.Notejot.p/src/Models/Trash.c io.github.lainsce.Notejot.p/src/Repositories/NoteRepository.c io.github.lainsce.Notejot.p/src/Repositories/NotebookRepository.c io.github.lainsce.Notejot.p/src/Repositories/TrashRepository.c io.github.lainsce.Notejot.p/src/Services/MigrationManager.c io.github.lainsce.Notejot.p/src/Services/SettingsManager.c io.github.lainsce.Notejot.p/src/Services/StyleManager.c io.github.lainsce.Notejot.p/src/Utils/FileUtils.c io.github.lainsce.Notejot.p/src/Utils/FormatUtils.c io.github.lainsce.Notejot.p/src/Utils/MiscUtils.c io.github.lainsce.Notejot.p/src/Utils/NoteSorter.c io.github.lainsce.Notejot.p/src/Utils/ObservableList.c io.github.lainsce.Notejot.p/src/Utils/ThreadUtils.c io.github.lainsce.Notejot.p/src/Utils/TimeUtils.c io.github.lainsce.Notejot.p/src/ViewModels/NoteViewModel.c io.github.lainsce.Notejot.p/src/ViewModels/NotebookViewModel.c io.github.lainsce.Notejot.p/src/ViewModels/TrashViewModel.c io.github.lainsce.Notejot.p/src/Views/NoteContentView.c io.github.lainsce.Notejot.p/src/Views/NoteGridView.c io.github.lainsce.Notejot.p/src/Views/NoteListView.c io.github.lainsce.Notejot.p/src/Views/NotebookListView.c io.github.lainsce.Notejot.p/src/Views/NotebookMainListView.c io.github.lainsce.Notejot.p/src/Views/NotebookMoveListView.c io.github.lainsce.Notejot.p/src/Views/TrashContentView.c io.github.lainsce.Notejot.p/src/Views/TrashListView.c io.github.lainsce.Notejot.p/src/Views/View.c io.github.lainsce.Notejot.p/src/Widgets/EditNotebookDialog.c io.github.lainsce.Notejot.p/src/Widgets/NoteGridRowContent.c io.github.lainsce.Notejot.p/src/Widgets/NoteRowBadge.c io.github.lainsce.Notejot.p/src/Widgets/NoteRowContent.c io.github.lainsce.Notejot.p/src/Widgets/MoveToDialog.c io.github.lainsce.Notejot.p/src/Widgets/NotebookRowContent.c io.github.lainsce.Notejot.p/src/Widgets/NoteTheme.c io.github.lainsce.Notejot.p/src/Widgets/TrashRowBadge.c io.github.lainsce.Notejot.p/src/Widgets/TrashRowContent.c                                                                                                        
2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.971 :: valac -C --debug --debug --target-glib=2.68 --pkg json-glib-1.0 --pkg gmodule-2.0 --pkg libadwaita-1 --pkg gee-0.8 --pkg gobject-2.0 --pkg glib-2.0 --pkg gtk4 --pkg gio-2.0 --color=always --directory io.github.lainsce.Notejot.p --basedir ../src/ --gresources=../src/data/io.github.lainsce.Notejot.gresource.xml /root/parts/notejot/src/src/Config.vapi ../src/src/Application.vala ../src/src/MainWindow.vala ../src/src/Models/Note.vala ../src/src/Models/Notebook.vala ../src/src/Models/Trash.vala ../src/src/Repositories/NoteRepository.vala ../src/src/Repositories/NotebookRepository.vala ../src/src/Repositories/TrashRepository.vala ../src/src/Services/MigrationManager.vala ../src/src/Services/SettingsManager.vala ../src/src/Services/StyleManager.vala ../src/src/Utils/FileUtils.vala ../src/src/Utils/FormatUtils.vala ../src/src/Utils/MiscUtils.vala ../src/src/Utils/NoteSorter.vala ../src/src/Utils/ObservableList.vala ../src/src/Utils/ThreadUtils.vala ../src/src/Utils/TimeUtils.vala ../src/src/ViewModels/NoteViewModel.vala ../src/src/ViewModels/NotebookViewModel.vala ../src/src/ViewModels/TrashViewModel.vala ../src/src/Views/NoteContentView.vala ../src/src/Views/NoteGridView.vala ../src/src/Views/NoteListView.vala ../src/src/Views/NotebookListView.vala ../src/src/Views/NotebookMainListView.vala ../src/src/Views/NotebookMoveListView.vala ../src/src/Views/TrashContentView.vala ../src/src/Views/TrashListView.vala ../src/src/Views/View.vala ../src/src/Widgets/EditNotebookDialog.vala ../src/src/Widgets/NoteGridRowContent.vala ../src/src/Widgets/NoteRowBadge.vala ../src/src/Widgets/NoteRowContent.vala ../src/src/Widgets/MoveToDialog.vala ../src/src/Widgets/NotebookRowContent.vala ../src/src/Widgets/NoteTheme.vala ../src/src/Widgets/TrashRowBadge.vala ../src/src/Widgets/TrashRowContent.vala                                         
2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.971 :: ../src/src/Utils/ThreadUtils.vala:40.13-40.95: warning: unhandled error `GLib.ThreadError'                                                                  
2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.971 ::    40 |             var tp = new ThreadPool<Worker>.with_owned_data (worker => worker.run (), 1, false);                                                    
2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.971 ::       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     
2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 :: ../src/src/Views/NoteContentView.vala:250.40-250.157: error: Equality operation: `bool' and `string' are incompatible                                       
2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 ::   250 |                 back2_button.visible = ((MainWindow)MiscUtils.find_ancestor_of_type<MainWindow>(this)).sgrid.get_visible_child_name () == "notegrid" != false ? true : false;                                                                                                                                                                                          
2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 ::       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                          
2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 :: Compilation failed: 1 error(s), 1 warning(s)                                                                                                                
2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 :: ninja: build stopped: subcommand failed.                                                                                   
```````````

**Comment by kenvandine** [comment]
> Well, there is actually lots of issue in the `paper` snap if built without any changes. But the prefix is necessary to be changed so that, it actually works, takes the snaps paths into consideration. I don't know if it'll work or not. I will actually need to change the dbus `exec` path then. Also, the description & summary isn't perfect yet. Kindly keep the `--prefix` unchanged.
> 
> Have you tested it locally? It builds without `gobject-introspection`?

Yes, gobject-introspection is included in the gnome-42-2204-sdk snap (I am the maintainer of that build-snap as well as the gnome extension).

The prefix hack shouldn't be necessary anymore, that is something we did in the past for some snaps but those issues should work properly with the gnome extension.

> Well, that's great, thanks for your PR. BTW, would like another help. Can you help me with this one?
> 
> ```
> [1/41] Compiling Vala source ../src/src/Application.vala ../src/src/MainWindow.vala ../src/src/Models/Note.vala ../src/src/Models/Notebook.vala ../src/src/Models/Trash.vala ../src/src/Repositories/NoteRepository.vala ../src/src/Repositories/NotebookRepository.vala ../src/src/Repositories/TrashRepository.vala ../src/src/Services/MigrationManager.vala ../src/src/Services/SettingsManager.vala ../src/src/Services/StyleManager.vala ../src/src/Utils/FileUtils.vala ../src/src/Utils/FormatUtils.vala ../src/src/Utils/MiscUtils.vala ../src/src/Utils/NoteSorter.vala ../src/src/Utils/ObservableList.vala ../src/src/Utils/ThreadUtils.vala ../src/src/Utils/TimeUtils.vala ../src/src/ViewModels/NoteViewModel.vala ../src/src/ViewModels/NotebookViewModel.vala ../src/src/ViewModels/TrashViewModel.vala ../src/src/Views/NoteContentView.vala ../src/src/Views/NoteGridView.vala ../src/src/Views/NoteListView.vala ../src/src/Views/NotebookListView.vala ../src/src/Views/NotebookMainListView.vala ../src/src/Views/NotebookMoveListView.vala ../src/src/Views/TrashContentView.vala ../src/src/Views/TrashListView.vala ../src/src/Views/View.vala ../src/src/Widgets/EditNotebookDialog.vala ../src/src/Widgets/NoteGridRowContent.vala ../src/src/Widgets/NoteRowBadge.vala ../src/src/Widgets/NoteRowContent.vala ../src/src/Widgets/MoveToDialog.vala ../src/src/Widgets/NotebookRowContent.vala ../src/src/Widgets/NoteTheme.vala ../src/src/Widgets/TrashRowBadge.vala ../src/src/Widgets/TrashRowContent.vala                                                                                                                                                        
> 2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.970 :: FAILED: io.github.lainsce.Notejot.p/src/Application.c io.github.lainsce.Notejot.p/src/MainWindow.c io.github.lainsce.Notejot.p/src/Models/Note.c io.github.lainsce.Notejot.p/src/Models/Notebook.c io.github.lainsce.Notejot.p/src/Models/Trash.c io.github.lainsce.Notejot.p/src/Repositories/NoteRepository.c io.github.lainsce.Notejot.p/src/Repositories/NotebookRepository.c io.github.lainsce.Notejot.p/src/Repositories/TrashRepository.c io.github.lainsce.Notejot.p/src/Services/MigrationManager.c io.github.lainsce.Notejot.p/src/Services/SettingsManager.c io.github.lainsce.Notejot.p/src/Services/StyleManager.c io.github.lainsce.Notejot.p/src/Utils/FileUtils.c io.github.lainsce.Notejot.p/src/Utils/FormatUtils.c io.github.lainsce.Notejot.p/src/Utils/MiscUtils.c io.github.lainsce.Notejot.p/src/Utils/NoteSorter.c io.github.lainsce.Notejot.p/src/Utils/ObservableList.c io.github.lainsce.Notejot.p/src/Utils/ThreadUtils.c io.github.lainsce.Notejot.p/src/Utils/TimeUtils.c io.github.lainsce.Notejot.p/src/ViewModels/NoteViewModel.c io.github.lainsce.Notejot.p/src/ViewModels/NotebookViewModel.c io.github.lainsce.Notejot.p/src/ViewModels/TrashViewModel.c io.github.lainsce.Notejot.p/src/Views/NoteContentView.c io.github.lainsce.Notejot.p/src/Views/NoteGridView.c io.github.lainsce.Notejot.p/src/Views/NoteListView.c io.github.lainsce.Notejot.p/src/Views/NotebookListView.c io.github.lainsce.Notejot.p/src/Views/NotebookMainListView.c io.github.lainsce.Notejot.p/src/Views/NotebookMoveListView.c io.github.lainsce.Notejot.p/src/Views/TrashContentView.c io.github.lainsce.Notejot.p/src/Views/TrashListView.c io.github.lainsce.Notejot.p/src/Views/View.c io.github.lainsce.Notejot.p/src/Widgets/EditNotebookDialog.c io.github.lainsce.Notejot.p/src/Widgets/NoteGridRowContent.c io.github.lainsce.Notejot.p/src/Widgets/NoteRowBadge.c io.github.lainsce.Notejot.p/src/Widgets/NoteRowContent.c io.github.lainsce.Notejot.p/src/Widgets/MoveToDialog.c io.github.lainsce.Notejot.p/src/Widgets/NotebookRowContent.c io.github.lainsce.Notejot.p/src/Widgets/NoteTheme.c io.github.lainsce.Notejot.p/src/Widgets/TrashRowBadge.c io.github.lainsce.Notejot.p/src/Widgets/TrashRowContent.c                                                                                                        
> 2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.971 :: valac -C --debug --debug --target-glib=2.68 --pkg json-glib-1.0 --pkg gmodule-2.0 --pkg libadwaita-1 --pkg gee-0.8 --pkg gobject-2.0 --pkg glib-2.0 --pkg gtk4 --pkg gio-2.0 --color=always --directory io.github.lainsce.Notejot.p --basedir ../src/ --gresources=../src/data/io.github.lainsce.Notejot.gresource.xml /root/parts/notejot/src/src/Config.vapi ../src/src/Application.vala ../src/src/MainWindow.vala ../src/src/Models/Note.vala ../src/src/Models/Notebook.vala ../src/src/Models/Trash.vala ../src/src/Repositories/NoteRepository.vala ../src/src/Repositories/NotebookRepository.vala ../src/src/Repositories/TrashRepository.vala ../src/src/Services/MigrationManager.vala ../src/src/Services/SettingsManager.vala ../src/src/Services/StyleManager.vala ../src/src/Utils/FileUtils.vala ../src/src/Utils/FormatUtils.vala ../src/src/Utils/MiscUtils.vala ../src/src/Utils/NoteSorter.vala ../src/src/Utils/ObservableList.vala ../src/src/Utils/ThreadUtils.vala ../src/src/Utils/TimeUtils.vala ../src/src/ViewModels/NoteViewModel.vala ../src/src/ViewModels/NotebookViewModel.vala ../src/src/ViewModels/TrashViewModel.vala ../src/src/Views/NoteContentView.vala ../src/src/Views/NoteGridView.vala ../src/src/Views/NoteListView.vala ../src/src/Views/NotebookListView.vala ../src/src/Views/NotebookMainListView.vala ../src/src/Views/NotebookMoveListView.vala ../src/src/Views/TrashContentView.vala ../src/src/Views/TrashListView.vala ../src/src/Views/View.vala ../src/src/Widgets/EditNotebookDialog.vala ../src/src/Widgets/NoteGridRowContent.vala ../src/src/Widgets/NoteRowBadge.vala ../src/src/Widgets/NoteRowContent.vala ../src/src/Widgets/MoveToDialog.vala ../src/src/Widgets/NotebookRowContent.vala ../src/src/Widgets/NoteTheme.vala ../src/src/Widgets/TrashRowBadge.vala ../src/src/Widgets/TrashRowContent.vala                                         
> 2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.971 :: ../src/src/Utils/ThreadUtils.vala:40.13-40.95: warning: unhandled error `GLib.ThreadError'                                                                  
> 2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.971 ::    40 |             var tp = new ThreadPool<Worker>.with_owned_data (worker => worker.run (), 1, false);                                                    
> 2023-03-29 23:30:57.038 :: 2023-03-29 18:00:53.971 ::       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     
> 2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 :: ../src/src/Views/NoteContentView.vala:250.40-250.157: error: Equality operation: `bool' and `string' are incompatible                                       
> 2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 ::   250 |                 back2_button.visible = ((MainWindow)MiscUtils.find_ancestor_of_type<MainWindow>(this)).sgrid.get_visible_child_name () == "notegrid" != false ? true : false;                                                                                                                                                                                          
> 2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 ::       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                          
> 2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 :: Compilation failed: 1 error(s), 1 warning(s)                                                                                                                
> 2023-03-29 23:30:57.039 :: 2023-03-29 18:00:53.971 :: ninja: build stopped: subcommand failed.                                                                                   
> ```

vala compiler error, maybe it's related to the valac version?

**Comment by soumyaDghosh** [comment]
Yeah, I got you. The dev himself is facing the issue with building in the latest version of flatpak. Any way to use older version of `valac`? 
BTW, my objective by snapping these projects is to bring the goodness of gnome-circle apps and libadwaita apps to ubuntu, What do u think about?

**Comment by kenvandine** [comment]
> Yeah, I got you. The dev himself is facing the issue with building in the latest version of flatpak. Any way to use older version of `valac`? BTW, my object by snapping these projects is to bring the goodness of gnome-circle apps and libadwaita apps to ubuntu, What do u think about?

You would need to build an older version of vala in your snap as a part and use that.  It might be complicated, but doable.  Feel free to reach out anytime.  You can usually find me in #ubuntu-desktop on Libera IRC or you can DM me on discord at https://discord.gg/ubuntu

**Comment by kenvandine** [comment]
> Yeah, I got you. The dev himself is facing the issue with building in the latest version of flatpak. Any way to use older version of `valac`? BTW, my object by snapping these projects is to bring the goodness of gnome-circle apps and libadwaita apps to ubuntu, What do u think about?

BTW, I think it's a great idea and I'm happy to help in any way I can.

**Comment by soumyaDghosh** [comment]
Hey, can I have your discord id? So, that I can have a one-to-one conversation with you? Actually as you offered me help, I am ready to take it, and there are a lot of projects which are there still not building up. In many case, the `gnome` extension is the culprit. I would ask your help for those.

**Pull request merged**
